# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 962f3724d3ea5bd77738d5966346f2dce38219954ecdb4baddb4380898b9912dc30cb6db152ed9224442636f1d55703229755a290cd06838c840c6ce614b0263

test:
  secret_key_base: 1fa5ca73a2b774b4b0e44a9a3b2f0b345799a935b7e6d643e489a40e92bae32bf5c0328ab631ac7c866a2fa1c367820ad7d3c93de28b14a576a09b4a0e8abfad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
